# Generated by Django 5.1.1 on 2024-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_email_doctor_password_alter_doctor_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='years_experience',
            new_name='yearsExperience',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurance',
            field=models.CharField(max_length=100),
        ),
    ]
