# Generated by Django 5.1.1 on 2024-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_years_experience_doctor_yearsexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Zcj68G8HSOPzjKtxJRyBF4$LhUy4xvX9+M8/mT0K2nPvDoQGXNXQvNEK6yWAIit24s=', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$YLRdIYYp2jMjCBo5BjBM6g$3+NlQ2nhBCtj93vIFIYKKkkTF900YdWwKcAk9CH6rZw=', max_length=100),
        ),
    ]
